sion_name: 3-panes
windows:
- window_name: dev window
  layout: main-vertical
  shell_command_before:
    - cd ~/
  panes:
    - shell_command:
        - cd ~/repo/khcp
        - vi
    - k8s
    - cd ~/repo/dotfiles
