session_name: "${REPO}"
start_directory: "~/repo/${REPO}"
global_options:
  automatic-rename: off
windows:
  - window_name: edit
    focus: "true"
    panes:
      - focus: "true"
        shell_command: nvim
  - window_name: run
    panes:
      - focus: "true"
